version: 0.2
env:
  git-credential-helper: yes
exported-variables:
  - CODEBUILD_RESOLVED_SOURCE_VERSION
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pwd
      - mkdir -p /opt/spark
      - cd /opt/spark
      - pwd
      - wget https://dlcdn.apache.org/spark/spark-3.1.2/spark-3.1.2-bin-hadoop2.7.tgz
      - tar xvf spark-3.1.2-bin-hadoop2.7.tgz
      - ls -al
      - which python
      - which java
      - java --version
      # - export JAVA_HOME=$(which java)
      - cd ~
      - export SPARK_HOME=/opt/spark/spark-3.1.2-bin-hadoop2.7 >> .bashrc
      - export PATH=$PATH:$SPARK_HOME/bin >> .bashrc
      - export PYSPARK_PYTHON=$(which python) >> .bashrc
      - pip install awsglue-local
  build:
    commands:
      # - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      # - git fetch
      # - test=$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION^)
      # - echo $test
      - cd ~
      - ls -al
      - cat .bashrc
      - source ~/.bashrc
      - pwd
      - git clone https://github.com/AmanPatwa/glue-test.git
      - ls
      # - NAME=$(git diff --name-only HEAD^)
      - cd glue-test
      - ls
      - spark-submit sunlife-aman-glue-test.py
      - name=$(git diff --name-only HEAD^)
      - name=$(echo $name)
      - echo $name
      - name1=$name
      - export name1
#   post_build:
#     commands:
#       - python --version
#       # - pip install aws_logging_handlers
#       - python test.py
# artifacts:
#   type: zip
#   files:
#     - '**/*'
