version: 0.2
env:
  git-credential-helper: yes
exported-variables:
  - CODEBUILD_RESOLVED_SOURCE_VERSION
phases:
  install:
    commands:
      - pwd
      # - cd ~
      # - git clone https://github.com/AmanPatwa/glue-test.git
      # - cd glue-test
      # - docker --version
      - docker build -t glue-script .
      # - cd ~
      # - docker images
      # - docker run -itd --name glue-container glue-script
      - docker ps
      # - git clone https://github.com/awslabs/aws-glue-libs.git
      # - wget https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-common/apache-maven-3.6.0-bin.tar.gz
      # - tar xvf apache-maven-3.6.0-bin.tar.gz
      # - wget https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-3.0/spark-3.1.1-amzn-0-bin-3.2.1-amzn-3.tgz
      # - tar xvf spark-3.1.1-amzn-0-bin-3.2.1-amzn-3.tgz
      # - ls -al
      # - export MAVEN=/root/apache-maven-3.6.0-bin
      # - export PATH=$PATH:$MAVEN/bin
      # - export SPARK_HOME=/root/spark-3.1.1-amzn-0-bin-3.2.1-amzn-3
      # - export PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin
      # - export PYSPARK_PYTHON=$(which python)
      # - pip install awsglue-local
      # - pip install pytest
      # - pip install pandas
  build:
    commands:
      - cd ~
      - git clone https://github.com/AmanPatwa/glue-test.git
      - cd glue-test
      - ls
      - name=$(git diff --name-only HEAD^)
      - name=$(echo $name)
      - echo $name
      - name1=$name
      - export name1
  # post_build:
  #   commands:
  #     # - python --version
  #     # - pip install aws_logging_handlers
      - python test.py
      - docker ps
      - docker stop $(docker ps -a -q)
      - docker rm $(docker ps -a -q)
artifacts:
  type: zip
  files:
    - '**/*'
