version: 0.2
env:
  git-credential-helper: yes
exported-variables:
  - CODEBUILD_RESOLVED_SOURCE_VERSION
phases:
  install:
    runtime-versions:
      python: 3.7
    # commands:
    #   - pwd
    #   - mkdir -p /opt/spark
    #   - cd /opt/spark
    #   - pwd
    #   - wget https://dlcdn.apache.org/spark/spark-3.1.2/spark-3.1.2-bin-hadoop2.7.tgz
    #   - tar xvf spark-3.1.2-bin-hadoop2.7.tgz
    #   - ls -al
    #   - which python
    #   - which java
    #   - java --version
    #   # - export JAVA_HOME=$(which java)
    #   - cd ~
    #   - export SPARK_HOME=/opt/spark/spark-3.1.2-bin-hadoop2.7 
    #   - export PATH=$PATH:$SPARK_HOME/bin::$SPARK_HOME/sbin
    #   - export PYSPARK_PYTHON=$(which python)
    #   - pip install awsglue-local
    commands:
      - git clone https://github.com/awslabs/aws-glue-libs.git
      - wget https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-common/apache-maven-3.6.0-bin.tar.gz
      - tar xvf apache-maven-3.6.0-bin.tar.gz
      - ls
      - wget https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-3.0/spark-3.1.1-amzn-0-bin-3.2.1-amzn-3.tgz
      - tar spark-3.1.1-amzn-0-bin-3.2.1-amzn-3.tgz
      - ls
      - export SPARK_HOME=spark-2.4.3-bin-spark-3.1.1-amzn-0-bin-3.2.1-amzn-3
      - pip install pyspark
  build:
    commands:
      # - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      # - git fetch
      # - test=$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION^)
      # - echo $test
      # - cd ~
      - ls -al
      - pwd
      - git clone https://github.com/AmanPatwa/glue-test.git
      - ls
      # - NAME=$(git diff --name-only HEAD^)
      - cd glue-test
      - ls
      - ./bin/gluesparksubmit sunlife-aman-glue-test.py
      - name=$(git diff --name-only HEAD^)
      - name=$(echo $name)
      - echo $name
      - name1=$name
      - export name1
#   post_build:
#     commands:
#       - python --version
#       # - pip install aws_logging_handlers
#       - python test.py
# artifacts:
#   type: zip
#   files:
#     - '**/*'
